version: 2
updates:
  # .github/workflows/*.yml
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"

  # Package
  - package-ecosystem: nuget
    directory: /InternetRelayChat/
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"

  # Examples
  - package-ecosystem: nuget
    directory: /InternetRelayChat.Examples/
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"

  # Tests
  - package-ecosystem: nuget
    directory: /InternetRelayChat.Tests/
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Europe/London
    groups:
      default:
        patterns:
          - "*"
